apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-server-cm
data:
  eureka_service_address: http://localhost:9000/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: discovery-server
  selector:
    app: discovery-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-server
spec:
  serviceName: "discovery-server"
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: wi-reviewz/ms-discovery-server:0.0.11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: discovery-server
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-cm
                  key: eureka_service_address
---                  
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-lb
  labels:
    app: discovery-server
spec:
  selector:
    app: discovery-server
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000